from __future__ import annotations

import html
import json
import math
import re
from typing import Any

from . import __version__
from .results import Comparison, Run


def text(value: Any) -> str:
    """Render source-controlled and input-controlled text as literal Markdown."""
    if isinstance(value, (dict, list)):
        value = json.dumps(value, sort_keys=True, ensure_ascii=True)
    elif value is None:
        value = "not recorded"
    elif isinstance(value, bool):
        value = str(value).lower()
    value = html.escape(str(value), quote=True)
    value = re.sub(r"([\\`*_{}\[\]()|~])", r"\\\1", value)
    return value.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "<br>")


def table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = ["| " + " | ".join(text(x) for x in headers) + " |"]
    lines.append("| " + " | ".join("---" for _ in headers) + " |")
    lines.extend("| " + " | ".join(text(x) for x in row) + " |" for row in rows)
    return "\n".join(lines)


def formatted(value: float | None, suffix: str = "") -> str:
    if value is None or not math.isfinite(value):
        return "n/a"
    # Significant figures keep sub-microsecond measurements and small ratios
    # visible without implying more precision than the input supports.
    return f"{value:.6g}{suffix}"


def ratio(numerator: float, denominator: float) -> float | None:
    value = numerator / denominator if denominator else None
    return value if value is not None and math.isfinite(value) else None


def change(numerator: float, denominator: float) -> str:
    value = ratio(numerator, denominator)
    percentage = (value - 1) * 100 if value is not None else None
    return (
        "n/a"
        if percentage is None or not math.isfinite(percentage)
        else f"{percentage:+.3f}%"
    )


def render_report(
    runs: dict[str, Run],
    comparisons: list[Comparison],
    *,
    title: str = "Direct-VM benchmark report",
    comparison_source: str | None = None,
    comparison_sha256: str | None = None,
) -> str:
    sections = [
        f"# {text(title)}",
        (
            f"Generated by monad-execbench-report {__version__} from saved results. "
            "No capture, verification, or benchmark execution was performed by this report command."
        ),
        "## Measurement scope",
        (
            "These are warmed direct-VM measurements of the root call and all nested calls "
            "against captured in-memory state, not node throughput or full-transaction latency. "
            "Fixture loading, cache priming/compilation, transaction-state setup/reset, "
            "correctness checks, and serialization are excluded from the runner's timed region. "
            "The runner verifies replay correctness before measuring; this report validates the "
            "saved result structure, not the fixture or its execution."
        ),
        (
            "Wall time is elapsed time; CPU time is process CPU time. All timings below are "
            "microseconds per execution. Each raw repetition already contains a calibrated "
            "average over its iterations. Statistics give equal weight to those repetition "
            "averages; aggregate JSON rows are not counted as additional samples. "
            "Execution gas excludes transaction-envelope accounting and must not be interpreted "
            "as transaction fees or as measured CPU cycles."
        ),
        "## Caveats",
        (
            "- CPU affinity, core isolation, CPU model, kernel, governor/turbo settings, and "
            "competing load are not all established by the current JSON. Matching provenance "
            "does not establish identical operating conditions; consult the original run logs.\n"
            "- Timing ratios are descriptive ratios of medians, not paired-sample estimates, "
            "confidence intervals, or statistical significance tests. Gas and timing do not "
            "establish security or functional equivalence between different cases.\n"
            "- A warning-free report is not a certification of publishable measurement quality. "
            "Console-only runner warnings cannot be recovered from these files."
        ),
    ]
    warnings = [
        f"- {text(alias)}: {text(warning)}"
        for alias, run in runs.items()
        for warning in run.warnings
    ]
    sections.append(
        "\n".join(warnings)
        if warnings
        else "No additional warnings were detected in the recorded fields."
    )
    sections.extend(
        [
            "## Input files",
            table(
                ["Input", "Mode", "Cases", "Result file", "SHA-256"],
                [
                    [
                        alias,
                        run.context["benchmark_mode"],
                        len(run.cases),
                        str(run.path),
                        run.sha256,
                    ]
                    for alias, run in runs.items()
                ],
            ),
        ]
    )
    if comparisons:
        sections.extend(
            [
                "## Explicit comparisons",
                (
                    "Every ratio is candidate / baseline, calculated within the same execution "
                    "mode and matching recorded fixture, runner, build, and host context. "
                    "A ratio above 1 means more gas or more time; a negative timing change means "
                    "less time. Different modes are reported separately, never pooled. "
                    "A zero denominator is shown as n/a."
                ),
                f"Comparison manifest: {text(comparison_source)}; SHA-256: {text(comparison_sha256)}.",
                table(
                    [
                        "Comparison",
                        "Baseline input / case",
                        "Candidate input / case",
                        "Mode",
                    ],
                    [
                        [
                            c.name,
                            f"{c.baseline_run.alias} / {c.baseline.name}",
                            f"{c.candidate_run.alias} / {c.candidate.name}",
                            c.baseline_run.context["benchmark_mode"],
                        ]
                        for c in comparisons
                    ],
                ),
                table(
                    [
                        "Comparison",
                        "Gas ratio",
                        "Wall median ratio",
                        "Wall change",
                        "CPU median ratio",
                        "CPU change",
                    ],
                    [
                        [
                            c.name,
                            formatted(ratio(c.candidate.gas, c.baseline.gas), "x"),
                            formatted(
                                ratio(c.candidate.wall.median, c.baseline.wall.median),
                                "x",
                            ),
                            change(c.candidate.wall.median, c.baseline.wall.median),
                            formatted(
                                ratio(c.candidate.cpu.median, c.baseline.cpu.median),
                                "x",
                            ),
                            change(c.candidate.cpu.median, c.baseline.cpu.median),
                        ]
                        for c in comparisons
                    ],
                ),
                (
                    "CPU microseconds per million execution gas = median CPU microseconds × "
                    "1,000,000 / execution gas. This normalization describes this workload; "
                    "it is not a universal conversion from gas to time."
                ),
                table(
                    [
                        "Comparison",
                        "Baseline CPU µs / million gas",
                        "Candidate CPU µs / million gas",
                    ],
                    [
                        [
                            c.name,
                            formatted(
                                c.baseline.cpu.median / c.baseline.gas * 1_000_000
                                if c.baseline.gas
                                else None
                            ),
                            formatted(
                                c.candidate.cpu.median / c.candidate.gas * 1_000_000
                                if c.candidate.gas
                                else None
                            ),
                        ]
                        for c in comparisons
                    ],
                ),
                (
                    "Pairing is explicitly supplied by the report author, not inferred from case names "
                    "or labels. Review the metadata below to confirm each pair answers the intended question."
                ),
            ]
        )
    else:
        sections.extend(
            [
                "## Comparisons",
                "No comparison manifest was supplied. No implementation pairings or ratios were inferred.",
            ]
        )
    for alias, run in runs.items():
        sections.extend(
            [
                f"## Input: {text(alias)}",
                "### Case summary",
                table(
                    [
                        "Case",
                        "Status",
                        "Repetitions",
                        "Total iterations",
                        "Execution gas",
                        "Logs",
                        "Return bytes",
                        "Wall median µs",
                        "CPU median µs",
                    ],
                    [
                        [
                            case.name,
                            case.status,
                            case.repetitions,
                            case.iterations,
                            case.gas,
                            case.logs,
                            case.output_bytes,
                            formatted(case.wall.median),
                            formatted(case.cpu.median),
                        ]
                        for case in run.cases.values()
                    ],
                ),
                "### Timing distributions",
                (
                    "Standard deviation is the sample standard deviation (n − 1). "
                    "CV is standard deviation / mean, displayed as a percentage. "
                    "Standard deviation requires at least two repetitions; CV also requires a "
                    "nonzero mean. Unavailable values are n/a, not zero."
                ),
                table(
                    [
                        "Case",
                        "Clock",
                        "Median µs",
                        "Mean µs",
                        "Min µs",
                        "Max µs",
                        "Stddev µs",
                        "CV",
                    ],
                    [
                        [
                            case.name,
                            clock,
                            formatted(d.median),
                            formatted(d.mean),
                            formatted(d.minimum),
                            formatted(d.maximum),
                            formatted(d.stddev),
                            formatted(d.cv * 100 if d.cv is not None else None, "%"),
                        ]
                        for case in run.cases.values()
                        for clock, d in (("wall", case.wall), ("CPU", case.cpu))
                    ],
                ),
                "### Case metadata",
                (
                    "Unsigned metadata counters below come from the exact decimal strings in "
                    "the JSON label, not the floating-point benchmark counters."
                ),
                table(
                    ["Case", "Labels", "Exact counters"],
                    [
                        [case.name, case.labels, case.counters]
                        for case in run.cases.values()
                    ],
                ),
                "### Recorded provenance",
                (
                    "All context fields are reproduced below. Paths describe the original capture/run "
                    "and need not exist on the reporting machine. Missing fields have not been inferred."
                ),
                table(
                    ["Field", "Recorded value"],
                    [[key, value] for key, value in sorted(run.context.items())],
                ),
            ]
        )
    return "\n\n".join(sections) + "\n"
